Programa 9
*&---------------------------------------------------------------------*
*& Report ZC00114 *
*&---------------------------------------------------------------------*
*& PROGRAMA PARA EXECUTAR COMANDOS EXTERNOS *
*& EXECUTA O COMANDO NO SERVIDOR *
*&---------------------------------------------------------------------*
REPORT ZC00114 .
* DEFINIR TABELA INTERNA COM A STRUCTURA DA TABELA BTCXPM
DATA : BEGIN OF t_btc OCCURS 0.
INCLUDE STRUCTURE BTCXPM.
DATA : END OF t_btc.
* DECLARAR UMA VARIAVEL COM O TIPO SXPGCOLIST-NAME
DATA wvar LIKE SXPGCOLIST-NAME.
* IGUALAR ESTA VARIAVEL AO COMANDO CRIADO NA SM69 PASSAR COMO PARAMETRO
wvar = 'ZCOMPLEX'.
INITIALIZATION.
START-OF-SELECTION.
PERFORM F_COMANDO_EXTERNO.
PERFORM F_MOSTRAR_TABELA.
END-OF-SELECTION.
*&---------------------------------------------------------------------*
*& Form F_COMANDO_EXTERNO
*&---------------------------------------------------------------------*
FORM F_COMANDO_EXTERNO .
* FUNÇÃO QUE IRA EXECUTAR O PARAMETRO
CALL FUNCTION 'SXPG_CALL_SYSTEM'
EXPORTING
COMMANDNAME = wvar
* ADDITIONAL_PARAMETERS = ' '
* IMPORTING
* STATUS =
* EXITCODE =
TABLES
EXEC_PROTOCOL = t_btc
EXCEPTIONS
NO_PERMISSION = 1
COMMAND_NOT_FOUND = 2
PARAMETERS_TOO_LONG = 3
SECURITY_RISK = 4
WRONG_CHECK_CALL_INTERFACE = 5
PROGRAM_START_ERROR = 6
PROGRAM_TERMINATION_ERROR = 7
X_ERROR = 8
PARAMETER_EXPECTED = 9
TOO_MANY_PARAMETERS = 10
ILLEGAL_COMMAND = 11
OTHERS = 12
.
IF SY-SUBRC <> 0.
MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
ENDFORM. " F_COMANDO_EXTERNO
*&---------------------------------------------------------------------*
*& Form F_MOSTRAR_TABELA
*&---------------------------------------------------------------------*
FORM F_MOSTRAR_TABELA .
CLEAR T_BTC.
LOOP AT T_BTC.
WRITE / T_BTC.
ENDLOOP.
ENDFORM. " F_MOSTRAR_TABELA